name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: Restart Server with New Code
        run: |
          docker-compose down
          docker-compose up -d --build
